# Generated by Django 5.1.15 on 2026-04-27 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firma', models.CharField(max_length=200)),
                ('ansprechpartner', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('mobil', models.CharField(blank=True, max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('branche', models.CharField(blank=True, max_length=100)),
                ('adresse', models.JSONField(blank=True, default=dict)),
                ('bewertung', models.IntegerField(blank=True, null=True)),
                ('zuverlaessigkeit', models.CharField(blank=True, choices=[('gering', 'Gering'), ('mittel', 'Mittel'), ('hoch', 'Hoch')], max_length=10)),
                ('ist_lieferant', models.BooleanField(default=False)),
                ('zahlungsziel_tage', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notiz', models.TextField(blank=True)),
                ('kennen_uns_ueber', models.CharField(blank=True, max_length=200)),
                ('foto_url', models.CharField(blank=True, max_length=500)),
                ('zuletzt_kontaktiert', models.DateTimeField(blank=True, null=True)),
                ('hero_crm_id', models.CharField(blank=True, max_length=100)),
                ('gespraechsnotizen', models.JSONField(blank=True, default=list)),
                ('sync_status', models.CharField(default='synced', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontakte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['firma'],
            },
        ),
    ]
