server {
    listen 443 ssl;
    ssl_certificate     /tmp/ssl/cert.pem;
    ssl_certificate_key /tmp/ssl/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    # API & Django direkt
    location /api/ {
        proxy_pass         http://django:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }
    location /admin/ {
        proxy_pass         http://django:8000;
        proxy_set_header   Host $host;
    }
    location /media/ {
        proxy_pass         http://django:8000;
        proxy_set_header   Host $host;
    }

    # Angular Dev-Server
    location / {
        proxy_pass         http://frontend:4200;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host localhost;
        proxy_read_timeout 86400;
    }
}
