# Generated by Django 5.1.15 on 2026-04-27 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_crm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('titel', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('typ', models.CharField(choices=[('aufmass', 'Aufmaß'), ('wartung', 'Wartung'), ('notdienst', 'Notdienst'), ('besprechung', 'Besprechung'), ('lieferung', 'Lieferung'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20)),
                ('status', models.CharField(choices=[('geplant', 'Geplant'), ('bestaetigt', 'Bestätigt'), ('abgesagt', 'Abgesagt'), ('erledigt', 'Erledigt')], default='geplant', max_length=20)),
                ('beginn', models.DateTimeField()),
                ('ende', models.DateTimeField()),
                ('ganztaegig', models.BooleanField(default=False)),
                ('adresse', models.JSONField(blank=True, default=dict)),
                ('kontakt_id', models.UUIDField(blank=True, null=True)),
                ('monteure', models.JSONField(default=list)),
                ('push_gesendet', models.BooleanField(default=False)),
                ('erinnerung_minuten', models.IntegerField(default=30)),
                ('notiz_id', models.UUIDField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['beginn'],
            },
        ),
    ]
