# Generated by Django 5.1.15 on 2026-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='erinnerung_ton',
            field=models.BooleanField(default=True),
        ),
    ]
