# Generated by Django 5.1.15 on 2026-05-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0002_termin_erinnerung_ton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='hero_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
