# Generated by Django 5.1.15 on 2026-05-04 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0003_alter_termin_hero_crm_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='hero_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='termin',
            unique_together={('hero_crm_id', 'erstellt_von')},
        ),
    ]
