# Generated by Django 5.1.15 on 2026-04-27 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('angebotsnummer', models.CharField(max_length=50, unique=True)),
                ('titel', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gesendet', 'Gesendet'), ('angenommen', 'Angenommen'), ('abgelehnt', 'Abgelehnt'), ('abgelaufen', 'Abgelaufen')], default='entwurf', max_length=20)),
                ('kunde', models.JSONField(default=dict)),
                ('positionen', models.JSONField(default=list)),
                ('notiz_id', models.UUIDField(blank=True, null=True)),
                ('nettobetrag', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mwst_prozent', models.IntegerField(default=19)),
                ('mwst_betrag', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bruttobetrag', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('zahlungsziel_tage', models.IntegerField(default=30)),
                ('gueltigkeit_tage', models.IntegerField(default=30)),
                ('freitext_kopf', models.TextField(blank=True)),
                ('freitext_fuss', models.TextField(blank=True)),
                ('ragflow_referenz_ids', models.JSONField(default=list)),
                ('pdf_url', models.CharField(blank=True, max_length=500)),
                ('version', models.IntegerField(default=1)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angebote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
