# Generated by Django 5.1.15 on 2026-05-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angebot',
            name='notiz_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
