# Generated by Django 5.1.15 on 2026-04-27 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('freitext', models.TextField(blank=True)),
                ('ki_text', models.TextField(blank=True, null=True)),
                ('ki_items', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='offen', max_length=20)),
                ('typ', models.CharField(choices=[('aufmass', 'Aufmaß'), ('begehung', 'Begehung'), ('wartung', 'Wartung'), ('notdienst', 'Notdienst'), ('allgemein', 'Allgemein')], default='allgemein', max_length=20)),
                ('hersteller_pills', models.JSONField(blank=True, default=list)),
                ('kategorien', models.JSONField(blank=True, default=list)),
                ('audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='NotizFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bild', models.ImageField(upload_to='notizen/fotos/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='notizen/thumbs/')),
                ('beschreibung', models.CharField(blank=True, max_length=255)),
                ('aufgenommen_am', models.DateTimeField(auto_now_add=True)),
                ('notiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='notizen.notiz')),
            ],
        ),
    ]
