# Generated by Django 5.1.15 on 2026-05-04 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagesbericht',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datum', models.DateField()),
                ('projekt_name', models.CharField(max_length=255)),
                ('projekt_adresse', models.JSONField(blank=True, default=dict)),
                ('wetter', models.CharField(blank=True, choices=[('sonnig', 'Sonnig'), ('bewoelkt', 'Bewölkt'), ('regen', 'Regen'), ('schnee', 'Schnee'), ('sturm', 'Sturm'), ('nebel', 'Nebel')], max_length=20)),
                ('temperatur', models.IntegerField(blank=True, null=True)),
                ('mitarbeiter', models.JSONField(default=list)),
                ('arbeiten_beschreibung', models.TextField(blank=True)),
                ('arbeiten_items', models.JSONField(default=list)),
                ('maengel', models.JSONField(default=list)),
                ('checkliste', models.JSONField(default=list)),
                ('unterschrift_auftraggeber', models.TextField(blank=True, null=True)),
                ('unterschrift_auftragnehmer', models.TextField(blank=True, null=True)),
                ('bemerkungen', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datum', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='TagesberichtFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bild', models.ImageField(upload_to='bautagebuch/fotos/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='bautagebuch/thumbs/')),
                ('beschreibung', models.CharField(blank=True, max_length=255)),
                ('typ', models.CharField(choices=[('arbeit', 'Arbeitsfortschritt'), ('mangel', 'Mangel'), ('vorher', 'Vorher'), ('nachher', 'Nachher'), ('allgemein', 'Allgemein')], default='allgemein', max_length=20)),
                ('aufgenommen_am', models.DateTimeField(auto_now_add=True)),
                ('tagesbericht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='bautagebuch.tagesbericht')),
            ],
        ),
    ]
